# Generated by Django 5.0 on 2023-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('skills', models.CharField(choices=[('js', 'JavaScript'), ('py', 'Python'), ('react', 'React.js'), ('redux', 'Redux')], default='js', max_length=20)),
                ('hero_image', models.URLField()),
                ('about', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
