# Generated by Django 5.0 on 2023-12-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('skills', models.TextField(blank=True)),
                ('hero_image', models.URLField()),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('connect_with_me', models.TextField(blank=True)),
            ],
        ),
    ]
