# Generated by Django 5.0 on 2023-12-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
