# Generated by Django 5.0 on 2023-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_userinfo_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='connect_with_me',
            field=models.TextField(blank=True),
        ),
    ]
