# Generated by Django 5.0 on 2023-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_userinfo_connect_with_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
