# Generated by Django 5.0 on 2023-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_userinfo_facebook_userinfo_github_userinfo_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='socials',
            field=models.TextField(null=True),
        ),
    ]
