# Generated by Django 5.0 on 2023-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_userinfo_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='socials',
        ),
    ]
