# Generated by Django 5.0 on 2023-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_education_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
