# Generated by Django 5.0 on 2023-12-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'InProgress'), (3, 'Complete')])),
            ],
        ),
    ]
