# Generated by Django 5.0 on 2023-12-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_examschedule_date_alter_examschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
